title: Dulek's Blog
author:
  name: Michał Dulko
  email: michal.dulko@gmail.com
description: >-
  My name is Michał Dulko. I work as an OpenShift and OpenStack developer at
  Red Hat. This blog will gather articles about the stuff I'm coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dulek.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

# Build settings
minima:
  social_links:
    linkedin: michał-dulko
    github: dulek
#  skin: dark

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima
