title: Michał Dulko Blog
author: Michał Dulko
email: michal.dulko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michał Dulko's development blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dulek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
