title: Dulek's Blog
author:
  name: Michał Dulko
  email: michal.dulko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The stuff I code at RH.

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
minima:
  social_links:
    github: dulek
    linkedin: michał-dulko
